# Generated by Django 6.0.2 on 2026-03-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='emergency_contact',
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='phone_number',
            field=models.CharField(help_text='Contact number', max_length=15),
        ),
    ]
