# Generated by Django 6.0.2 on 2026-03-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_deliveryperson_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('delivery_person', 'Delivery Person'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
