# Generated by Django 6.0.2 on 2026-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(blank=True, help_text='e.g. Near the big white gate', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='location_name',
            field=models.CharField(blank=True, help_text="e.g. Home, Office, Friend's House", max_length=100, null=True),
        ),
    ]
